CREATE TABLE fornecedor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   empresa VARCHAR(255),
   nome VARCHAR(255),
   tipo_empresa SMALLINT,
   email VARCHAR(255),
   telefone VARCHAR(255),
   endereco VARCHAR(255),
   ativo BOOLEAN NOT NULL,
   CONSTRAINT pk_fornecedor PRIMARY KEY (id)
);

CREATE TABLE medida_unidade (
  produto_capa_sku BIGINT NOT NULL,
   medida_unidade INTEGER
);

CREATE TABLE produto_capa (
  sku BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   description VARCHAR(255),
   fornecedor_id BIGINT,
   percas BIGINT,
   saldo BIGINT,
   preco_unitario DOUBLE PRECISION,
   valor DOUBLE PRECISION,
   minimo BIGINT,
   maximo BIGINT,
   resuprimento SMALLINT,
   ativo BOOLEAN NOT NULL,
   CONSTRAINT pk_produtocapa PRIMARY KEY (sku)
);

CREATE TABLE tipo_produto (
  produto_capa_sku BIGINT NOT NULL,
   tipo_produto INTEGER
);

CREATE TABLE produto_entrada (
  sku BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   numero_nota BIGINT,
   data_pedido TIMESTAMP WITHOUT TIME ZONE,
   data_entrega TIMESTAMP WITHOUT TIME ZONE,
   preco_compra DOUBLE PRECISION,
   quantidade BIGINT,
   observacao VARCHAR(255),
   CONSTRAINT pk_produtoentrada PRIMARY KEY (sku)
);

CREATE TABLE produto_perda (
  sku BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   data TIMESTAMP WITHOUT TIME ZONE,
   quantidade BIGINT,
   motivo VARCHAR(255),
   CONSTRAINT pk_produtoperda PRIMARY KEY (sku)
);

CREATE TABLE produto_saida (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   sku BIGINT,
   data_saida TIMESTAMP WITHOUT TIME ZONE,
   quantidade BIGINT,
   retirado_por VARCHAR(255),
   setor SMALLINT,
   obersvacao VARCHAR(255),
   CONSTRAINT pk_produtosaida PRIMARY KEY (id)
);


ALTER TABLE produto_capa ADD CONSTRAINT FK_PRODUTOCAPA_ON_FORNECEDOR FOREIGN KEY (fornecedor_id) REFERENCES fornecedor (id);

ALTER TABLE medida_unidade ADD CONSTRAINT fk_medida_unidade_on_produto_capa FOREIGN KEY (produto_capa_sku) REFERENCES produto_capa (sku);

ALTER TABLE tipo_produto ADD CONSTRAINT fk_tipo_produto_on_produto_capa FOREIGN KEY (produto_capa_sku) REFERENCES produto_capa (sku);