CREATE TABLE produto_capa (
  sku BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   description VARCHAR(255),
   tipo_produto SMALLINT,
   medida_unidade SMALLINT,
   fornecedor_id BIGINT,
   minimo BIGINT,
   maximo BIGINT,
   resuprimento SMALLINT,
   ativo BOOLEAN NOT NULL,
   CONSTRAINT pk_produtocapa PRIMARY KEY (sku)
);


CREATE TABLE fornecedor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   empresa VARCHAR(255),
   nome VARCHAR(255),
   tipo_empresa SMALLINT,
   email VARCHAR(255),
   telefone VARCHAR(255),
   endereco VARCHAR(255),
   ativo BOOLEAN NOT NULL,
   CONSTRAINT pk_fornecedor PRIMARY KEY (id)
);

CREATE TABLE produto_entrada (
  sku BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   numero_nota BIGINT,
   data_pedido TIMESTAMP WITHOUT TIME ZONE,
   data_entrega TIMESTAMP WITHOUT TIME ZONE,
   preco_compra DOUBLE PRECISION,
   quantidade BIGINT,
   observacao VARCHAR(255),
   CONSTRAINT pk_produtoentrada PRIMARY KEY (sku)
);

ALTER TABLE fornecedor ADD CONSTRAINT uc_fornecedor_empresa UNIQUE (empresa);

ALTER TABLE produto_capa ADD CONSTRAINT uc_produtocapa_description UNIQUE (description);

ALTER TABLE produto_capa ADD CONSTRAINT FK_PRODUTOCAPA_ON_FORNECEDOR FOREIGN KEY (fornecedor_id) REFERENCES fornecedor (id);

