
    create sequence revisao_seq start with 1 increment by 1;

    create table fornecedor (
        ativo boolean not null,
        tipo_empresa int check (tipo_empresa between 0 and 1),
        created_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_modified_date timestamp(6) with time zone not null,
        created_by varchar(255),
        email varchar(255) null,
        empresa varchar(255) unique,
        endereco varchar(255),
        last_modified_by varchar(255),
        nome varchar(255),
        telefone varchar(255),
        primary key (id)
    );

    create table fornecedor_aud (
        ativo boolean,
        revtype int,
        tipo_empresa int check (tipo_empresa between 0 and 1),
        id bigint not null,
        last_modified_date timestamp(6) with time zone,
        rev bigint not null,
        revend bigint,
        revend_tstmp timestamp(6),
        email varchar(255),
        empresa varchar(255),
        endereco varchar(255),
        last_modified_by varchar(255),
        nome varchar(255),
        telefone varchar(255),
        primary key (id, rev)
    );

    create table produto_capa (
        ativo boolean not null,
        cod_sistema integer,
        medida_unidade int not null check (medida_unidade between 0 and 10),
        resuprimento int check (resuprimento between 0 and 4),
        tipo_produto int not null check (tipo_produto between 0 and 2),
        created_date timestamp(6) with time zone not null,
        fornecedor_id bigint,
        id bigint generated by default as identity,
        last_modified_date timestamp(6) with time zone not null,
        maximo bigint,
        minimo bigint,
        created_by varchar(255),
        description varchar(255) unique,
        last_modified_by varchar(255),
        primary key (id)
    );

    create table produto_entrada (
        preco_compra float(53) check (preco_compra>=0),
        created_date timestamp(6) with time zone not null,
        data_entrega timestamp(6),
        data_pedido timestamp(6),
        id bigint generated by default as identity,
        last_modified_date timestamp(6) with time zone not null,
        numero_nota bigint,
        produto_capa_id bigint not null,
        quantidade bigint check (quantidade>=0),
        created_by varchar(255),
        last_modified_by varchar(255),
        observacao varchar(255),
        primary key (id)
    );

    create table produto_perda (
        created_date timestamp(6) with time zone not null,
        data timestamp(6),
        id bigint generated by default as identity,
        last_modified_date timestamp(6) with time zone not null,
        produto_capa_id bigint not null,
        quantidade bigint check (quantidade>=0),
        created_by varchar(255),
        last_modified_by varchar(255),
        motivo varchar(255),
        primary key (id)
    );

    create table produto_saida (
        setor int not null check (setor between 0 and 4),
        created_date timestamp(6) with time zone not null,
        data_saida timestamp(6),
        id bigint generated by default as identity,
        last_modified_date timestamp(6) with time zone not null,
        produto_capa_id bigint not null,
        quantidade bigint check (quantidade>=0),
        unidade_produtiva_id bigint,
        created_by varchar(255),
        last_modified_by varchar(255),
        observacao varchar(255),
        retirado_por varchar(255),
        primary key (id)
    );

    create table profiles (
        profiles integer,
        user_id integer not null
    );

    create table profiles_aud (
        profiles integer not null,
        revtype int,
        user_id integer not null,
        rev bigint not null,
        revend bigint,
        revend_tstmp timestamp(6),
        primary key (profiles, user_id, rev)
    );

    create table revisao (
        revisao_data timestamp(6),
        revisao_id bigint not null,
        ip varchar(255),
        usuario varchar(255),
        primary key (revisao_id)
    );

    create table unidade_produtiva (
        ativo boolean not null,
        created_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        last_modified_date timestamp(6) with time zone not null,
        created_by varchar(255),
        last_modified_by varchar(255),
        nome varchar(255) not null unique,
        servico varchar(255),
        primary key (id)
    );

    create table users (
        ativo boolean not null,
        id integer generated by default as identity,
        created_date timestamp(6) with time zone not null,
        last_modified_date timestamp(6) with time zone not null,
        created_by varchar(255),
        last_modified_by varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table users_aud (
        ativo boolean,
        id integer not null,
        revtype int,
        last_modified_date timestamp(6) with time zone,
        rev bigint not null,
        revend bigint,
        revend_tstmp timestamp(6),
        last_modified_by varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id, rev)
    );

    alter table if exists fornecedor_aud
       add constraint FKb0xtx8so9lipejhgndn56raad
       foreign key (rev)
       references revisao;

    alter table if exists fornecedor_aud
       add constraint FKs8x6uial9ykwq0va1j2otynma
       foreign key (revend)
       references revisao;

    alter table if exists produto_capa 
       add constraint FKdfx9c4dpjcmhhfu489uw99m5b 
       foreign key (fornecedor_id) 
       references fornecedor;

    alter table if exists produto_entrada 
       add constraint FKntyatok8kdnrane299jlh31k5 
       foreign key (produto_capa_id) 
       references produto_capa;

    alter table if exists produto_perda 
       add constraint FKeeo483woi23migqtf53xecuh1 
       foreign key (produto_capa_id) 
       references produto_capa;

    alter table if exists produto_saida 
       add constraint FK6c7jc6irqsdcgkihr2d9pjcdt 
       foreign key (produto_capa_id) 
       references produto_capa;

    alter table if exists produto_saida 
       add constraint FKk1m54px4u5r9s17ocarsoeqjw 
       foreign key (unidade_produtiva_id) 
       references unidade_produtiva;

    alter table if exists profiles 
       add constraint FK410q61iev7klncmpqfuo85ivh 
       foreign key (user_id) 
       references users;

    alter table if exists profiles_aud 
       add constraint FKicabrwem54c318yirowr3s0r 
       foreign key (rev) 
       references revisao;

    alter table if exists profiles_aud 
       add constraint FKpa1kbcrnduf7g16e1a1npc9lh 
       foreign key (revend) 
       references revisao;

    alter table if exists users_aud 
       add constraint FKm6lm3q3tj9y3t5j5plwywf0qa 
       foreign key (rev) 
       references revisao;

    alter table if exists users_aud 
       add constraint FKjnht6h13wawwimfxmfp4kohjm 
       foreign key (revend) 
       references revisao;